server:
  port: 80
spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: postgres
    password: root123
    url: jdbc:postgresql://localhost:5432/data_rest
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
